In [1]:
import pandas as pd

# 데이터 불러오기

In [4]:
df = pd.read_csv('./data/서울시5대범죄.csv', encoding='UTF-8')
df.head()

ParserError: Error tokenizing data. C error: EOF inside string starting at row 312

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   년도         200 non-null    int64
 1   자치구별       200 non-null    object
 2   살인발생       200 non-null    int64
 3   살인검거       200 non-null    int64
 4   강도발생       200 non-null    int64
 5   강도검거       200 non-null    int64
 6   강간·강제추행발생  200 non-null    int64
 7   강간·강제추행검거  200 non-null    int64
 8   절도발생       200 non-null    int64
 9   절도검거       200 non-null    int64
 10  폭력발생       200 non-null    int64
 11  폭력검거       200 non-null    int64
 12  발생합계       200 non-null    int64
 13  인구수        200 non-null    int64
dtypes: int64(13), object(1)
memory usage: 22.0+ KB

# 범죄율, 범죄율 순위 구하기
- 인구대비범죄율 (범죄 발생 건수 / 인구수) * 10만
- 범죄 발생 건수의 차이를 비교하기 쉽기 때문에 10만명으로 잡는다

In [6]:
# 범죄율 구하기(소수점 2자리로)
df['인구대비범죄율'] = (df['발생합계'] / df['인구수'] * 100000).round(2)

print(df)

       년도 자치구별  살인발생  살인검거  강도발생  강도검거  강간·강제추행발생  강간·강제추행검거  절도발생  절도검거  \
0    2014  종로구     3     7    12    15        226        948  2272  1281
1    2014   중구     6     5    13    13        221        161  2576   887
2    2014  용산구     1     2     7     7        213        169  1560   522
3    2014  성동구     1     1     5     6        141        103  1753   529
4    2014  광진구     8     9    16    22        249        199  3167  1001
..    ...  ...   ...   ...   ...   ...        ...        ...   ...   ...
195  2021  관악구     8     4     7     6        321        269  1860   929
196  2021  서초구     9     9     5     5        312        228  1503   691
197  2021  강남구    12    11    25    23        578        454  2372  1160
198  2021  송파구     3     3     7     6        247        216  2024   995
199  2021  강동구     3     3     6     6        124        103  1612   889

     폭력발생  폭력검거  발생합계     인구수  인구대비범죄율
0    2508  2359  5021  165344  3036.70
1    2415  2122  5231  136227  3839.91
2    2018  1640  3799  249914  1520.12
3    1682  1409  3582  303891  1178.71
4    2828  2300  6268  377375  1660.95
..    ...   ...   ...     ...      ...
195  2248  1926  4444  499449   889.78
196  1827  1506  3656  416167   878.49
197  3159  2749  6146  537800  1142.80
198  2433  2046  4714  663965   709.98
199  1713  1461  3458  466472   741.31

[200 rows x 15 columns]

In [8]:
# 범죄율순위 구하기
df["범죄율등수"] = (df.groupby("년도")['인구대비범죄율'].rank(ascending=False).astype(int))

df

,년도,자치구별,살인발생,살인검거,강도발생,강도검거,강간·강제추행발생,강간·강제추행검거,절도발생,절도검거,폭력발생,폭력검거,발생합계,인구수,인구대비범죄율,범죄율등수
0,2014,종로구,3,7,12,15,226,948,2272,1281,2508,2359,5021,165344,3036.70,2
1,2014,중구,6,5,13,13,221,161,2576,887,2415,2122,5231,136227,3839.91,1
2,2014,용산구,1,2,7,7,213,169,1560,522,2018,1640,3799,249914,1520.12,5
3,2014,성동구,1,1,5,6,141,103,1753,529,1682,1409,3582,303891,1178.71,16
4,2014,광진구,8,9,16,22,249,199,3167,1001,2828,2300,6268,377375,1660.95,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2021,관악구,8,4,7,6,321,269,1860,929,2248,1926,4444,499449,889.78,8
196,2021,서초구,9,9,5,5,312,228,1503,691,1827,1506,3656,416167,878.49,9
197,2021,강남구,12,11,25,23,578,454,2372,1160,3159,2749,6146,537800,1142.80,3
198,2021,송파구,3,3,7,6,247,216,2024,995,2433,2046,4714,663965,709.98,18
199,2021,강동구,3,3,6,6,124,103,1612,889,1713,1461,3458,466472,741.31,15

# 수정된 데이터프레임 저장하기(.CSV)

In [9]:
df.to_csv('서울시5대범죄전처리.csv')