## 문제 1.
- 주어진 리스트에 대해 아래 과정을 차례로 수행한 최종 결괏값을 출력하시오.
```[2, 3, 3.2, 5, 7.5, 10, 11.8, 12, 23, 25, 31.5, 34]```

- 제 1사분위수와 제 3사분위수를 구하시오.
- 제 1사분위수와 제 3사분위수 차이의 절댓값을 구하시오.
- 그 값의 소수점을 버린 후 정수로 출력하시오.

In [1]:
import pandas as pd
import numpy as np

a = [2, 3, 3.2, 5, 7.5, 10, 11.8, 12, 23, 25, 31.5, 34]
a

[2, 3, 3.2, 5, 7.5, 10, 11.8, 12, 23, 25, 31.5, 34]

In [5]:
q1 = np.quantile(a, 0.25)
q3 = np.quantile(a, 0.75)
diff = q1-q3
result = int(abs(diff))

print(f'Q1 : {q1}')
print(f'Q3 : {q3}')
print(f'result : {result}')

Q1 : 4.55
Q3 : 23.5
result : 18

## 문제 2. 
- 주어진 facebook 데이터 세트는 페이스북 라이브에 대한 사용자 반응을 집계한 것이다. 이 중 love 반응(num_loves)과 wow 반응(num_wows)을 매우 긍정적인 반응이라고 정의할 때, 전체 반응 수(num_reaction) 중 매우 긍정적인 반응 수가 차지하는 비율을 계산하시오. 그리고 그 비율이 0.5보다 작고, 0.4보다 크며 유형이 비디오에 해당하는 건수를 정수로 출력하시오.

In [7]:
import pandas as pd 
df = pd.read_csv("data/4회/402_facebook.csv")
df.head()

,status_id,status_type,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys
0,246675545449582_1649696485147474,video,529,512,262,432,92,3,1,1,0
1,246675545449582_1649426988507757,photo,150,0,0,150,0,0,0,0,0
2,246675545449582_1648730588577397,video,227,236,57,204,21,1,1,0,0
3,246675545449582_1648576705259452,photo,111,0,0,111,0,0,0,0,0
4,246675545449582_1645700502213739,photo,213,0,0,204,9,0,0,0,0

In [10]:
df['ratio'] = (df['num_loves'] + df['num_wows']) / df['num_reactions']
df.head()

,status_id,status_type,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,ratio
0,246675545449582_1649696485147474,video,529,512,262,432,92,3,1,1,0,0.179584
1,246675545449582_1649426988507757,photo,150,0,0,150,0,0,0,0,0,0.000000
2,246675545449582_1648730588577397,video,227,236,57,204,21,1,1,0,0,0.096916
3,246675545449582_1648576705259452,photo,111,0,0,111,0,0,0,0,0,0.000000
4,246675545449582_1645700502213739,photo,213,0,0,204,9,0,0,0,0,0.042254

In [13]:
rst_df = df[(0.4<df['ratio']) & (df['ratio']<0.5) & (df['status_type']=='video')]
print(len(rst_df))

90

## 문제 3. 
- 주어진 netflix 데이터 세트는 넷플릭스에 등록된 컨텐츠의 메타 데이터이다. 2018년 1월에 넷플릭스에 등록된 컨텐츠 중에서 'United Kingdom'이 단독 제작한 컨텐츠의 수를 정수로 출력하시오.

### 풀이1

In [114]:
import pandas as pd 
df = pd.read_csv("data/4회/403_netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [118]:
rst_df = df[(df['date_added'].str.contains('January'))&(df['date_added'].str.contains('2018'))&(df['country']=='United Kingdom')]
print(len(rst_df))

6

### 풀이2

In [105]:
import pandas as pd 
df = pd.read_csv("data/4회/403_netflix.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [106]:
df['date_added'] = pd.to_datetime(df['date_added'])
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [107]:
rst_df = df[(df['date_added'].dt.year == 2018.0) & (df['date_added'].dt.month == 1.0) & (df['country'] == 'United Kingdom')]
print(len(rst_df))

6